version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    depends_on:
      - nexus

  nexus:
    image: sonatype/nexus3:3.46.0
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
      - ./log4j2.xml:/opt/sonatype/nexus/etc/log4j2.xml  # Add this line
      - ./org.ops4j.pax.logging.cfg:/opt/sonatype/nexus/etc/karaf/org.ops4j.pax.logging.cfg
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Dnexus.security.obfuscate.passwords=false -Dlog4j.configurationFile=file:/opt/sonatype/nexus/etc/log4j2.xml
      - NEXUS_CONTEXT=

volumes:
  nexus-data: